### ISSUE TITLE
Logo Design For Mediation Diary

### ISSUE THREAD

**Issue by zularizal** [javiyt/meditationdiary#6]
Hi @javiyt , I'm a graphic designer, I'm interested in your project. Therefore, I want to contribute by creating a free logo for your project. What do you think?

**Comment by javiyt** [comment]
@zularizal thanks for your offer, of course you can contribute creating a free logo and any other design you can help with, I'm really bad designing apps ;)

**Comment by zularizal** [comment]
Hi @javiyt , sorry to reply late, this is the logo for your project. This logo is inspired by people, books and handshakes.

What about color, which do you think looks good?

If there is something you want to change, let me know.

![bitmap](https://user-images.githubusercontent.com/38547278/50733486-f1d26000-11c0-11e9-9875-bb2b54a8be6e.png)
